iTube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from stream_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('login_app.urls')),
    path('stream/', include('stream_app.urls')),
    path('', views.home, name='home'),
    path('services/', include('services.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login_app/urls.py
from django.urls import path
from . import views

app_name = "login_app"

urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('login/', views.login_page, name='login'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout_user, name='logout'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
]

stream_app/urls.py
from django.urls import path
from . import views

app_name = "stream_app"

urlpatterns = [
    path('', views.home, name='home'),
    path('upload-video/', views.upload_video, name='upload_video'),
    path('video-detail/<slug:slug>/', views.details, name='video_details'),
    path('edit-video/<slug:slug>/', views.edit_video, name='edit_video'),
]

login_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    profile_picture = models.ImageField(upload_to='display_pictures', blank=True)
    about = models.CharField(blank=True, max_length=101)
    fullname = models.CharField(max_length=255, blank=True)
    website = models.URLField(blank=True)

    def __str__(self):
        return self.user.username

login_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Profile

# sign up form
class SignUpForm(UserCreationForm):
    username = forms.CharField(
        required=True,
        label="",
        widget=forms.TextInput(attrs={'placeholder': 'username'}) 
    )
    email = forms.EmailField(
        required=True,
        label="",
        widget=forms.TextInput(attrs={'placeholder': 'user@domain.com'}),
        #unique = True
    )
    password1 = forms.CharField(
        required=True,
        label="",
        widget=forms.PasswordInput(attrs={'placeholder': 'password'}) 
    )
    password2 = forms.CharField(
        required=True,
        label="",
        widget=forms.PasswordInput(attrs={'placeholder': 're-enter the password'}) 
    )
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

# login form
class LoginForm(AuthenticationForm):
    username = forms.CharField(
        required=True,
        label="",
        widget=forms.TextInput(attrs={'placeholder': 'Username'}) 
    )
    password = forms.CharField(
        required=True,
        label="",
        widget=forms.PasswordInput(attrs={'placeholder': 'Password'}) 
    )
    class Meta:
        model = User
        fields = ['Username', 'Password']

# edit profile form
class EditProfile(forms.ModelForm):
    fullname = forms.CharField(
        required=False,
        label="Full name",
    )
    class Meta:
        model = Profile
        exclude = ['user']

login_app/views.py
# framework imports
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


# project imports
from .forms import SignUpForm, LoginForm, EditProfile
from .models import Profile
from stream_app.models import Video

# Create your views here.

def sign_up(request):
    form = SignUpForm()
    if request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            user_profile = Profile(user=user)
            user_profile.save()
            return HttpResponseRedirect(reverse('login_app:login'))

    return render(request, 'login_app/sign_up.html', {'form': form})

def login_page(request):
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('stream_app:home'))

    return render(request, 'login_app/login.html', {'form': form})

@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('stream_app:home'))

@login_required
def profile(request):
    return render(request, 'login_app/profile.html', {})



@login_required
def edit_profile(request):
    current_user = Profile.objects.get(user=request.user)
    form = EditProfile(instance=current_user)
    if request.method == 'POST':
        form = EditProfile(request.POST, request.FILES, instance=current_user)
        if form.is_valid():
            form.save()
            # form = EditProfile(instance=current_user)
            return HttpResponseRedirect(reverse('login_app:profile'))
            
    return render(request, 'login_app/edit_profile.html', {'form': form})

templates/login_app/edit_profile.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Edit profile {% endblock %}
{% block css_block %}
<style>
    .edit-profile{
        width: 725px;
        border: 1px solid #ccc;
        padding: 40px;
    }
</style>
{% endblock %}
{% block body_block %}

<div class='edit-profile'>
    <h5>Edit your profile</h5>
    <form method="POST" enctype="multipart/form-data">
      {{ form|crispy}}
      {% csrf_token %}
      <button type="submit" style="width:100%" class="btn btn-primary">Update</button>
    </form>
  </div>

{% endblock %}

templates/login_app/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Login {% endblock %}
{% block css_block %}
<style>
    .sign-up{
        width: 425px;
        border: 1px solid #ccc;
        padding: 40px;
    }
    .login{
        width: 425px;
        border: 1px solid #ccc;
        padding: 40px;
    }
</style>
{% endblock %}
{% block body_block %}
<center>
<div class="form-container">
    <div class="sign-up">
        <h4>Login here</h4><br>
        <form action="" method="POST">
            {{form|crispy}}
            {% csrf_token %}
            <button type="submit" class="btn btn-primary btn-sm">Login</button>
        </form>
    </div>
    <div class="login my-3">
        <p>Don't have an account? <a href="{% url 'login_app:sign_up' %}">Sign up here</a></p>
    </div>
</div>
</center>
{% endblock %}

templates/login_app/profile.html
{% extends 'navbar.html' %}
{%block title_block %} Profile {%endblock%}

{% block body_block %}

<!-- user profile section -->

<div class="row">
    <div class="col-sm-4">
        {% if user.profile.profile_picture %}
        <img src="/media/{{user.profile.profile_picture}}" alt="" width="250px" height="250px"
            class="rounded-circle">
        {% else %}
        <img src="/static/images/unisex_avatar.jpg" width="250px" height="250px" class="rounded-circle" alt="default">
        {% endif %}
    </div>
    <div class="col-sm-8"><br><br>
        <strong>Full name: </strong>{{user.profile.fullname}} <br>
        <strong>User name: </strong>{{user.username}} <br>
        <strong>Email address: </strong> {{user.email}} <br>
        <strong>Website: </strong><a href="{{user.profile.website}}">Click here to visit</a><br>
        <strong>About: </strong>{{user.profile.about}} <br><br>
        <a href="{% url 'login_app:edit_profile' %}" class="btn btn-info btn-sm">Edit profile</a> &nbsp;
        <a href="{% url 'stream_app:upload_video' %}" class="btn btn-primary btn-sm">Upload video</a>
    </div>
</div><hr>

<!-- user video section -->

<div class="my-videos">
    <div class="row p-5">
        {% for video in user.post_user.all %}
        <div class="col-sm-6">
            <img src="/media/{{video.thumbnail}}" alt="" width="425"><br>
            <Strong>{{video.video_title}}</Strong> <br>
            <small class="text-muted"><strong>Publish date: </strong>{{video.publish_date}}</small><br>
            <small class="text-muted"><strong>Updated on: </strong>{{video.update_date}}</small> <br>
            <b>{{video.video_comment.count}} Comments</b> &nbsp; 
            <a href="{% url 'stream_app:edit_video' slug=video.slug %}" class="btn btn-secondary btn-sm">Edit Video</a>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/login_app/sign_up.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Sign up {% endblock %}
{% block css_block %}
<style>
    .sign-up{
        width: 425px;
        border: 1px solid #ccc;
        padding: 40px;
    }
    .login{
        width: 425px;
        border: 1px solid #ccc;
        padding: 40px;
    }
</style>
{% endblock %}
{% block body_block %}
<center>
<div class="form-container">
    <div class="sign-up">
        <h4>Sign Up here</h4><br>
        <form action="" method="POST">
            {{form|crispy}}
            {% csrf_token %}
            <div class="d-flex justify-content-center mt-3 login_container">
                <input class="btn login_btn" type="submit" value="Register Account">
              </div>
        </form>
    </div>
    <div class="login my-3">
        <p>Have an account? <a href="{% url 'login_app:login' %}">Login here</a></p>
    </div>
</div>
</center>

{% endblock %}